### ISSUE TITLE
Bug dans la timeline après déplacement d'élément

### ISSUE THREAD

**Issue by jjugand** [philharmoniedeparis/metascore-library#398]
Quand on déplace en vertical dans la timeline un élément, la ligne rose permettant d'identifier son déplacement à tendance à rester affichée. On ne peut alors plus déplacer horizontalement l'élément en question ni retailler ses temps de début et de fin. J'ai du à chaque fois sauvegarder puis recharger la page pour pouvoir le faire.
Guide W6Lv
https://mybrowser.fyi/report/5e873abd10ea4c0015061066

**Comment by semiaddict** [comment]
Sauf erreur de ma part, il me semble que cela n'est plus d'actualité dans la v3.
