### ISSUE TITLE
Certains liens d'API ne fonctionnent pas sous Chrome

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/metascore-library#428]
Ne fonctionne plus (cliquer sur "intervalle ascendant") :
https://pad.philharmoniedeparis.fr/0729148-symphonie-n1-ludwig-van-beethoven.aspx

Fonctionne :
https://pad.philharmoniedeparis.fr/0765070-symphonie-n-40-de-wolfgang-amadeus-mozart.aspx

**Comment by semiaddict** [comment]
Je ferme ce cas, car il semble que l'application concernée ait déjà été migrée.
