### ISSUE TITLE
Chevauchement des éléments

### ISSUE THREAD

**Issue by fgoubault** [philharmoniedeparis/metascore-library#519]
Pour faire suite à la discussion que nous avons eue à l'une des dernières réunions. 

La précision des time codes semble variable d'un support/navigateur à l'autre. Exemple dans _Pierre et le Loup_ 
(Pierre et le loup de Serge Prokofiev [copy] - Copie pour test timecode, guide n5DY) : sur IPad mini 2021, Safari, chevauchement des réponses dans la partie "Instruments" (exemple : cliquer sur le Basson puis la réponse "le chat").

**Comment by semiaddict** [comment]
Cela semble être dû à la précision du timing des médias dans le navigateur, et peut dépendre de divers facteurs (encodage des médias, processeur, etc.).
Il est donc recommandé d'espacer les composants dans le temps, afin d'éviter les chevauchements.
