### ISSUE TITLE
Liens de comportement ne fonctionnent pas sur un scénario dupliqué

### ISSUE THREAD

**Issue by afborneuf** [philharmoniedeparis/metascore-library#622]
Je viens de faire un guide avec 2 scénarios (VmOo)
Une fois mes deux scénarios en place, j'ai implémenté des comportements dans le premier scénario (= faire apparaître 3 blocs texte cachés au démarrage en cliquant sur le mots "crédits")

Puis j'ai voulu faire la même chose dans le 2e scénario et là j'ai eu la surprise de retrouver les comportements que j'avais faits pour le premier scénario. Par curiosité je n'ai rien touché, mais, évidemment, dans le 2e scénario, les comportements ne fonctionnent pas.
Par sécurité, je n'ai plus rien touché car j'ai l'impression qu'en fait, les comportements ne sont pas dispatchés pas scénarios.

**Comment by semiaddict** [comment]
Je rouvre ce cas, car les lien de comportements dans un scénario activé par un lien ne semblent toujours pas fonctionner.
