### ISSUE TITLE
Copier-Coller d'éléments texte génère de multiples copies

### ISSUE THREAD

**Issue by rbailly** [philharmoniedeparis/metascore-library#638]
Julien:
"Le copier coller d'élément texte peut te faire apparaitre plus d'une dizaine de copie superposées. Je n'ai pas eu l'impression que le bug était systématique mais il m'arrive assez régulièrement"

**Comment by semiaddict** [comment]
Je ferme ce cas, car nous ne pouvons pas le reproduire (sauf sous Windows 7, qui a un bug dans la gestion des événements du clavier).
