### ISSUE TITLE
Permettre de supprimer toutes les images-clé d'un curseur via le menu contextuel

### ISSUE THREAD

**Issue by semiaddict** [philharmoniedeparis/metascore-library#677]
Voir https://github.com/philharmoniedeparis/metascore-library/issues/672#issuecomment-1522794991 pour plus d'info.

**Comment by afborneuf** [comment]
Est-ce que cela a été mis en prod ? Je ne trouve pas comment l'on fait !

**Comment by semiaddict** [comment]
Oui, c'est en prod.
C'est l'option "_Supprimer toutes les positions_" dans le menu contextuel : 

![image](https://github.com/user-attachments/assets/dd4325c9-8881-4aff-a728-a72c2ac3afb4)
