### ISSUE TITLE
Permettre un changement dans l'ordre des scénarios 

### ISSUE THREAD

**Issue by pmilli444** [philharmoniedeparis/metascore-library#697]
Bonjour Oussama,

Je trouve qu'il serait utile de pouvoir modifier l'ordre des scénarios sur lesquels on n'est pas en train de travailler. 

Pour l'instant, si je veux modifier la position d'un scénario, je dois le dupliquer, puis effacer l'original. Cela peut se révéler très laborieux quand on travaille sur plusieurs scénarios.

Merci.

Bien à toi,

Pietro

**Comment by semiaddict** [comment]
C'est en place sur dev.
