### ISSUE TITLE
avec firefox, l'ascenseur de la timeline empêche l'utilisation de la poignée permettant d'ajuster le temps d'un composant

### ISSUE THREAD

**Issue by pmilli444** [philharmoniedeparis/metascore-library#709]
### Problem

Si on utilise Firefox et qu'on veut modifier le temps d'un composant avec la poignée blanche, on ne peut pas tout le temps le faire car l'ascenseur cache la poignée.

![ascenseur](https://github.com/philharmoniedeparis/metascore-library/assets/145785422/2f6ca750-9f30-4215-9937-6f0335ae6d3c)

### Expected behavior

L'ascenseur ne devrait pas se superposer à la poignée.

### Reproduction steps

```bash
1. Aller au niveau de la timeline.
2. Essayer d'attraper la poignée d'un composant qui va jusqu'à la fin de la timeline.
3. L'ascenseur cache la poignée.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

**Comment by semiaddict** [comment]
Ceci est un duplicata de #385, pour lequel je n'ai malheureusement pas encore de solution viable.
