### ISSUE TITLE
Permettre la réinitialisation de l'application si elle est inactive pendant un certain temps

### ISSUE THREAD

**Issue by semiaddict** [philharmoniedeparis/metascore-library#718]
### Suggestion

Ajouter les blocs de comportement suivants pour permettre la réinitialisation de l'application si elle est inactive pendant un certain temps :

- un bloc `l'application est inactive depuis ... secondes` qui renvoie la valeur « vrai » si l'application est restée inactive pendant une période donnée, et « faux » dans le cas contraire
- un bloc `réinitialiser l'application`, qui réinitialise l'état de l'application

**Comment by semiaddict** [comment]
C'est en place sur dev.

Voici un exemple de mises en place :

![image](https://github.com/user-attachments/assets/a7684ee1-0e03-428c-a966-38860cb3e6e5)

**Comment by afborneuf** [comment]
Bonjour Oussama, je viens de tester ça sur le guide #lO7M en dev, mais cela semble ne pas fonctionner... ai-je fait une bêtise ?
Merci.

**Comment by semiaddict** [comment]
Bonjour Anne-Florence,
Je ne sais pas pourquoi, mais le code ne fonctionne pas lorsqu'il est compilé en mode production.
J'ai, pour l'instant, recompilé le code en mode développement, et il semble fonctionner correctement.
Je poursuivrai mes recherches la semaine prochaine pour comprendre pourquoi le code ne fonctionne pas lorsqu'il est compilé en mode production.

**Comment by semiaddict** [comment]
J'ai résolu le problème en mode production via c9f9c73b62bf3f8504c0e9d45f264e6a8700c226.

**Comment by afborneuf** [comment]
Merci Oussama. Le comportement fonctionne désormais sur le guide #lO7M en dev. Peux-tu passer en production s'il te plaît ?

**Comment by semiaddict** [comment]
> Merci Oussama. Le comportement fonctionne désormais sur le guide #lO7M en dev. Peux-tu passer en production s'il te plaît ?

C'est fait.

**Comment by afborneuf** [comment]
Bonjour Oussama. Juste une question à propos de ce que signifie "inactivité"...
J'ai intégré le comportement "après 10 secondes d'inactivité, réinitialiser l'application" dans #Y6ln. Effectivement, lorsque le lecteur ne fait rien, l'application est réinitialisée. Par contre il semblerait que la simple lecture (play) soit aussi considérée comme de l'inactivité car après 10 secondes de lecture, l'app est réinitialisée. Est-ce normal ?

**Comment by semiaddict** [comment]
Bonjour Anne-Florence,

La durée d'inactivité est totalement dissociée du fait que la lecture est en cours ou non.
Cela donne plus de possibilités.
C'est pourquoi, dans mon exemple ci-dessus, je vérifie également que la lecture n'est pas en cours.

**Comment by afborneuf** [comment]
Ah... désolée, j'ai refait le comportement toute seule sans consulter ton exemple et je n'ai effectivement pas ajouté la condition "non la lecture est en cours"... ça devrait mieux marcher maintenant !

**Comment by afborneuf** [comment]
Un autre petit inconvénient... Je n'arrive pas à trouver comment je pourrais y remédier... Lorsque je lance un lien d'écoute dont la durée est > au temps au bout duquel mon application doit être réinitialisée, l'application se réinitialise dès la fin de l'écoute. Comment faire pour que le décompte du temps avant réinitialisation ne commence qu'après la fin de la lecture ?

Exemple : dans le guide #Y6ln, la réinitialisation est réglée après 10 secondes d'inactivité. En cliquant par exemple sur "Écouter le thème 1" l'écoute dure environ 43 secondes et l'appli est donc réinitialisée dès la fin de l'écoute, alors que je souhaiterais qu'elle ne soit réinitialisée que 10 secondes après la fin de l'écoute.

**Comment by semiaddict** [comment]
Bonsoir Anne-Florence,

Cela n'est en effet pas possible avec le fonctionnement actuel. Je n'avais pas pensé à ce cas d'usage.
Peut-être que, contrairement à ce que je pensais initialement, il serait préférable de calculer le temps d'inactivité uniquement lorsque le média n'est pas en cours de lecture.
L'idée initiale derrière le comportement actuel était de permettre la réinitialisation des médias longs lorsqu'il n'y a pas eu d'interaction de l'utilisateur, même si la lecture est en cours.

En tout cas, 10 secondes me semble être une période assez courte pour une réinitialisation, non ?
Penses-tu qu'augmenter le temps de réinitialisation au temps du lien d'écoute le plus long + 10 secondes fonctionnerait dans ton cas ?

Nous pouvons en discuter de vive voix si tu préfères.

**Comment by afborneuf** [comment]
Merci Oussama pour ce retour... oui, parlons-en de vive voix, je suis disponible toute la journée

**Comment by semiaddict** [comment]
Il a donc été convenu de remplacer le fonctionnement actuel pour tenir compte de l'état de la lecture dans le calcul de la durée d'inactivité;

**Comment by semiaddict** [comment]
C'est en place en dev et prod.
