### ISSUE TITLE
impossible d'éditer un texte

### ISSUE THREAD

**Issue by afborneuf** [philharmoniedeparis/metascore-library#722]
### Problem

Lorsqu'un élément Texte est sélectionné et que je clique sur "éditer le texte", une roue se met à tourner indéfiniment.

### Expected behavior

... éditer le texte

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Firefox

### OS

Windows

**Comment by semiaddict** [comment]
@afborneuf, peux-tu essayer de vider le cache de ton navigateur ?

**Comment by afborneuf** [comment]
Merci ! Désolée.
